// <auto-generated />
using ExamWeb_NguyenDoanThanhVu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_LieuHoangPhuc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_LieuHoangPhuc.Models.DiaNhac", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<double>("GiaBan")
                    .HasColumnType("float");

                b.Property<string>("NgheSi")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("SoLuong")
                    .HasColumnType("int");

                b.Property<bool>("TrongNuoc")
                    .HasColumnType("bit");

                b.Property<string>("TuaCD")
                    .HasMaxLength(250)
                    .HasColumnType("nvarchar(250)");

                b.HasKey("Id");

                b.ToTable("diaNhacs");
            });
#pragma warning restore 612, 618
        }
    }
}
